/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewNovo;

import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;

import javax.swing.JOptionPane;

import Control.*;
import Model.buscaAvancada;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabs
 */
public class Principal extends javax.swing.JFrame {

    private ConexaoBD con;
    private buscaNormalNatureza buscaNormal;
    private consultaHistorico historico;
    private buscaAvancadaRes buscaAvancada;
    private DefaultTableModel model;
    private consultaBasica consultaBas;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lblItensObrigatorios.setVisible(false);
        lblAnoInvalido.setVisible(false);
        lblAnoInvalido.setForeground(Color.red);
        lblItensObrigatorios.setForeground(Color.red);
        txtFieldConsultaSimples.setToolTipText("Insira aqui uma natureza de despesa ou programa.");
        txtFieldNatureza1.setToolTipText("Insira aqui o tipo de natureza que deseja pesquisar.");
        txtFieldNatureza2.setToolTipText("Campo adicional de tipo de natureza.");
        txtFieldDataInicial.setToolTipText("Ano inicial do período.");
        txtFieldDataFinal.setToolTipText("Ano final do período.");
        txtFieldValorInicial.setToolTipText("Valor mínimo.");
        txtFieldValorFinal.setToolTipText("Valor máximo.");

        // é feito a conexão com o banco
        con = new ConexaoBD();

        jComboBoxMunicipio.removeAllItems();
        jComboBoxMunicipio2.removeAllItems();

		// é preenchido no formulário da consulta básica (especificamente o jComboBoxMunicipio)
        // os municípios presentes no banco de dados
        ArrayList<String> municipios = new consultaBasica(con).getMunicipio();
        int i;
        for (i = 0; i < municipios.size(); i++) {
            jComboBoxMunicipio.addItem(municipios.get(i));
            jComboBoxMunicipio2.addItem(municipios.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new RoundedPanel();
        pnlLabelMenuConsultas = new RoundedPanel();
        lblConsultas = new javax.swing.JLabel();
        pnlBordaBotoes = new javax.swing.JPanel();
        btConsultaSimples = new javax.swing.JButton();
        btConsultaAvancada = new javax.swing.JButton();
        btHistorico = new javax.swing.JButton();
        pnlHeader = new RoundedPanel();
        pnlCardLayout = new RoundedPanel();
        pnlConsultaSimples = new RoundedPanel();
        txtFieldConsultaSimples = new RoundJTextField(25);
        jRButtonNatureza = new javax.swing.JRadioButton();
        jRButtonPrograma = new javax.swing.JRadioButton();
        btPesquisarCSimples = new javax.swing.JButton();
        jComboBoxMunicipio = new javax.swing.JComboBox();
        lblMunicipioSimples = new javax.swing.JLabel();
        pnlConsultaAvancada = new RoundedPanel();
        lblItensObrigatorios = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblNatureza1 = new javax.swing.JLabel();
        lblNatureza2 = new javax.swing.JLabel();
        lblDataInicial = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        lblValorInicial = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();
        lblAnoInvalido = new javax.swing.JLabel();
        txtFieldNatureza1 = new RoundJTextField(25);
        txtFieldNatureza2 = new RoundJTextField(25);
        txtFieldDataInicial = new RoundJTextField(25);
        txtFieldDataFinal = new RoundJTextField(25);
        txtFieldValorInicial = new RoundJTextField(25);
        txtFieldValorFinal = new RoundJTextField(25);
        btPesquisarCAvancada = new javax.swing.JButton();
        jComboBoxMunicipio2 = new javax.swing.JComboBox();
        pnlResultadoConsultaSimples = new RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaSimples = new javax.swing.JTable();
        pnlResultadoConsultaAvancada = new RoundedPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultaAvancada = new javax.swing.JTable();
        pnlHistorico = new RoundedPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultaHistorico = new javax.swing.JTable();
        lblRodape = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas Públicas");

        pnlPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(687, 419));

        pnlMenu.setBackground(new java.awt.Color(204, 204, 204));
        pnlMenu.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.setName("pnlMenu"); // NOI18N

        pnlLabelMenuConsultas.setBackground(new java.awt.Color(102, 102, 102));
        pnlLabelMenuConsultas.setForeground(new java.awt.Color(102, 102, 102));

        lblConsultas.setBackground(new java.awt.Color(255, 255, 255));
        lblConsultas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblConsultas.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultas.setLabelFor(pnlMenu);
        lblConsultas.setText("Consultas");

        javax.swing.GroupLayout pnlLabelMenuConsultasLayout = new javax.swing.GroupLayout(pnlLabelMenuConsultas);
        pnlLabelMenuConsultas.setLayout(pnlLabelMenuConsultasLayout);
        pnlLabelMenuConsultasLayout.setHorizontalGroup(
            pnlLabelMenuConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelMenuConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLabelMenuConsultasLayout.setVerticalGroup(
            pnlLabelMenuConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelMenuConsultasLayout.createSequentialGroup()
                .addComponent(lblConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBordaBotoes.setBackground(new java.awt.Color(204, 204, 204));
        pnlBordaBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btConsultaSimples.setBackground(new java.awt.Color(0, 0, 51));
        btConsultaSimples.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConsultaSimples.setForeground(new java.awt.Color(255, 255, 255));
        btConsultaSimples.setText("Consulta Simples");
        btConsultaSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaSimplesActionPerformed(evt);
            }
        });

        btConsultaAvancada.setBackground(new java.awt.Color(0, 102, 153));
        btConsultaAvancada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConsultaAvancada.setForeground(new java.awt.Color(255, 255, 255));
        btConsultaAvancada.setText("Consulta Avançada");
        btConsultaAvancada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaAvancadaActionPerformed(evt);
            }
        });

        btHistorico.setBackground(new java.awt.Color(0, 102, 153));
        btHistorico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btHistorico.setForeground(new java.awt.Color(255, 255, 255));
        btHistorico.setText("Histórico");
        btHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBordaBotoesLayout = new javax.swing.GroupLayout(pnlBordaBotoes);
        pnlBordaBotoes.setLayout(pnlBordaBotoesLayout);
        pnlBordaBotoesLayout.setHorizontalGroup(
            pnlBordaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBordaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConsultaSimples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultaAvancada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBordaBotoesLayout.setVerticalGroup(
            pnlBordaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBordaBotoesLayout.createSequentialGroup()
                .addComponent(btConsultaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaAvancada, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btHistorico.getAccessibleContext().setAccessibleName("historico");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLabelMenuConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBordaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLabelMenuConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBordaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlHeader.setBackground(new java.awt.Color(0, 102, 153));
        pnlHeader.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        pnlCardLayout.setBackground(new java.awt.Color(204, 204, 204));
        pnlCardLayout.setForeground(new java.awt.Color(204, 204, 204));
        pnlCardLayout.setLayout(new java.awt.CardLayout());

        pnlConsultaSimples.setBackground(new java.awt.Color(204, 204, 204));
        pnlConsultaSimples.setForeground(new java.awt.Color(204, 204, 204));

        txtFieldConsultaSimples.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldConsultaSimples.setText("Pesquise...");
        txtFieldConsultaSimples.setCaretColor(new java.awt.Color(102, 102, 102));
        txtFieldConsultaSimples.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtFieldConsultaSimples.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldConsultaSimplesFocusGained(evt);
            }
        });

        btGroup.add(jRButtonNatureza);
        jRButtonNatureza.setText("Natureza");
        jRButtonNatureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonNaturezaActionPerformed(evt);
            }
        });

        btGroup.add(jRButtonPrograma);
        jRButtonPrograma.setText("Programa");
        jRButtonPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonProgramaActionPerformed(evt);
            }
        });

        btPesquisarCSimples.setBackground(new java.awt.Color(0, 102, 153));
        btPesquisarCSimples.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisarCSimples.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisarCSimples.setText("Pesquisar");
        btPesquisarCSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCSimplesActionPerformed(evt);
            }
        });

        jComboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMunicipioSimples.setText("Município:");

        javax.swing.GroupLayout pnlConsultaSimplesLayout = new javax.swing.GroupLayout(pnlConsultaSimples);
        pnlConsultaSimples.setLayout(pnlConsultaSimplesLayout);
        pnlConsultaSimplesLayout.setHorizontalGroup(
            pnlConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaSimplesLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(pnlConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaSimplesLayout.createSequentialGroup()
                        .addComponent(jRButtonNatureza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRButtonPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMunicipioSimples)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisarCSimples))
                    .addComponent(txtFieldConsultaSimples))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlConsultaSimplesLayout.setVerticalGroup(
            pnlConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaSimplesLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(txtFieldConsultaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRButtonNatureza)
                        .addComponent(jRButtonPrograma)
                        .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMunicipioSimples))
                    .addComponent(btPesquisarCSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlConsultaSimples, "pnlConsultaSimples");

        pnlConsultaAvancada.setBackground(new java.awt.Color(204, 204, 204));
        pnlConsultaAvancada.setForeground(new java.awt.Color(204, 204, 204));

        lblItensObrigatorios.setForeground(new java.awt.Color(255, 0, 0));
        lblItensObrigatorios.setText("Itens Obrigatórios");
        lblItensObrigatorios.setName("itemObrigatorio"); // NOI18N

        lblMunicipio.setText("Município:");

        lblNatureza1.setText("Natureza 1:");

        lblNatureza2.setText("Natureza 2:");

        lblDataInicial.setText("Ano Inicial:");

        lblDataFinal.setText("Ano Final:");

        lblValorInicial.setText("Valor Inicial:");

        lblValorFinal.setText("Valor Final:");

        lblAnoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        lblAnoInvalido.setText("Ano Inválido");
        lblAnoInvalido.setName("anoAviso"); // NOI18N

        txtFieldNatureza1.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldNatureza1.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFieldNatureza2.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldNatureza2.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFieldDataInicial.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldDataInicial.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFieldDataFinal.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldDataFinal.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFieldValorInicial.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldValorInicial.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFieldValorFinal.setForeground(new java.awt.Color(102, 102, 102));
        txtFieldValorFinal.setCaretColor(new java.awt.Color(102, 102, 102));

        btPesquisarCAvancada.setBackground(new java.awt.Color(0, 102, 153));
        btPesquisarCAvancada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisarCAvancada.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisarCAvancada.setText("Pesquisar");
        btPesquisarCAvancada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCAvancadaActionPerformed(evt);
            }
        });

        jComboBoxMunicipio2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlConsultaAvancadaLayout = new javax.swing.GroupLayout(pnlConsultaAvancada);
        pnlConsultaAvancada.setLayout(pnlConsultaAvancadaLayout);
        pnlConsultaAvancadaLayout.setHorizontalGroup(
            pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMunicipio)
                            .addComponent(lblNatureza1)
                            .addComponent(lblDataInicial)
                            .addComponent(lblValorInicial))
                        .addGap(18, 18, 18)
                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtFieldDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDataFinal))
                                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldNatureza1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldValorInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNatureza2)
                                            .addComponent(lblValorFinal))))
                                .addGap(18, 18, 18)
                                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btPesquisarCAvancada)
                                            .addComponent(txtFieldValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(47, Short.MAX_VALUE))
                                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldNatureza2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                                .addComponent(jComboBoxMunicipio2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                        .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblItensObrigatorios)
                            .addComponent(lblAnoInvalido))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlConsultaAvancadaLayout.setVerticalGroup(
            pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaAvancadaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMunicipio)
                    .addComponent(jComboBoxMunicipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNatureza2)
                    .addComponent(txtFieldNatureza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldNatureza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNatureza1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicial)
                    .addComponent(lblDataFinal)
                    .addComponent(txtFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorFinal)
                    .addComponent(txtFieldValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorInicial))
                .addGap(27, 27, 27)
                .addComponent(btPesquisarCAvancada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItensObrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnoInvalido)
                .addContainerGap())
        );

        pnlCardLayout.add(pnlConsultaAvancada, "pnlConsultaAvancada");

        pnlResultadoConsultaSimples.setBackground(new java.awt.Color(204, 204, 204));
        pnlResultadoConsultaSimples.setForeground(new java.awt.Color(204, 204, 204));

        tblConsultaSimples.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsultaSimples);

        javax.swing.GroupLayout pnlResultadoConsultaSimplesLayout = new javax.swing.GroupLayout(pnlResultadoConsultaSimples);
        pnlResultadoConsultaSimples.setLayout(pnlResultadoConsultaSimplesLayout);
        pnlResultadoConsultaSimplesLayout.setHorizontalGroup(
            pnlResultadoConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoConsultaSimplesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultadoConsultaSimplesLayout.setVerticalGroup(
            pnlResultadoConsultaSimplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoConsultaSimplesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCardLayout.add(pnlResultadoConsultaSimples, "pnlResultadoConsultaSimples");

        pnlResultadoConsultaAvancada.setBackground(new java.awt.Color(204, 204, 204));
        pnlResultadoConsultaAvancada.setForeground(new java.awt.Color(204, 204, 204));

        tblConsultaAvancada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblConsultaAvancada);

        javax.swing.GroupLayout pnlResultadoConsultaAvancadaLayout = new javax.swing.GroupLayout(pnlResultadoConsultaAvancada);
        pnlResultadoConsultaAvancada.setLayout(pnlResultadoConsultaAvancadaLayout);
        pnlResultadoConsultaAvancadaLayout.setHorizontalGroup(
            pnlResultadoConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoConsultaAvancadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultadoConsultaAvancadaLayout.setVerticalGroup(
            pnlResultadoConsultaAvancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoConsultaAvancadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCardLayout.add(pnlResultadoConsultaAvancada, "pnlResultadoConsultaAvancada");

        pnlHistorico.setBackground(new java.awt.Color(204, 204, 204));
        pnlHistorico.setForeground(new java.awt.Color(204, 204, 204));
        pnlHistorico.setName("pnlHistorico"); // NOI18N

        tblConsultaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblConsultaHistorico);

        javax.swing.GroupLayout pnlHistoricoLayout = new javax.swing.GroupLayout(pnlHistorico);
        pnlHistorico.setLayout(pnlHistoricoLayout);
        pnlHistoricoLayout.setHorizontalGroup(
            pnlHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHistoricoLayout.setVerticalGroup(
            pnlHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCardLayout.add(pnlHistorico, "pnlHistorico");
        pnlHistorico.getAccessibleContext().setAccessibleName("pnlHistorico");
        pnlHistorico.getAccessibleContext().setAccessibleParent(pnlCardLayout);

        lblRodape.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblRodape.setForeground(new java.awt.Color(0, 51, 102));
        lblRodape.setText("2015");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRodape)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(lblRodape)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pnlPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultaSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaSimplesActionPerformed
        CardLayout cl = (CardLayout) (pnlCardLayout.getLayout());

        cl.show(pnlCardLayout, "pnlConsultaSimples");

        btConsultaSimples.setBackground(new java.awt.Color(0, 0, 51));
        btHistorico.setBackground(new java.awt.Color(0, 102, 153));
        btConsultaAvancada.setBackground(new java.awt.Color(0, 102, 153));

        setTitle("Consulta Simples");

    }//GEN-LAST:event_btConsultaSimplesActionPerformed

    private void btConsultaAvancadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaAvancadaActionPerformed
        CardLayout c2 = (CardLayout) (pnlCardLayout.getLayout());

        c2.show(pnlCardLayout, "pnlConsultaAvancada");

        btConsultaAvancada.setBackground(new java.awt.Color(0, 0, 51));
        btHistorico.setBackground(new java.awt.Color(0, 102, 153));
        btConsultaSimples.setBackground(new java.awt.Color(0, 102, 153));

        setTitle("Consulta Avançada");
    }//GEN-LAST:event_btConsultaAvancadaActionPerformed

    private void txtFieldConsultaSimplesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldConsultaSimplesFocusGained
        if (txtFieldConsultaSimples.getText().equals("Pesquise...") || txtFieldConsultaSimples.getText().equals("Pesquise por Natureza") || txtFieldConsultaSimples.getText().equals("Pesquise por Programa")) {
            txtFieldConsultaSimples.setText("");
        }
    }//GEN-LAST:event_txtFieldConsultaSimplesFocusGained

    private void jRButtonNaturezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonNaturezaActionPerformed
        if (txtFieldConsultaSimples.getText().equals("Pesquise...") || txtFieldConsultaSimples.getText().equals("Pesquise por Programa") || txtFieldConsultaSimples.getText().equals("")) {
            txtFieldConsultaSimples.setText("Pesquise por Natureza");
        }

        txtFieldConsultaSimples.setToolTipText("Insira aqui uma natureza de despesa.");
    }//GEN-LAST:event_jRButtonNaturezaActionPerformed

    private void jRButtonProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonProgramaActionPerformed
        if (txtFieldConsultaSimples.getText().equals("Pesquise...") || txtFieldConsultaSimples.getText().equals("Pesquise por Natureza") || txtFieldConsultaSimples.getText().equals("")) {
            txtFieldConsultaSimples.setText("Pesquise por Programa");
        }

        txtFieldConsultaSimples.setToolTipText("Insira aqui um programa.");
    }//GEN-LAST:event_jRButtonProgramaActionPerformed

    private void btPesquisarCSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCSimplesActionPerformed
        String consulta = null;
            // verificação de erros no formulário
        // verifica se o campo de busca esta vazio e também, se o campo possui o texto padrão "Pesquise..."
        if (!txtFieldConsultaSimples.getText().isEmpty()) {
            if (txtFieldConsultaSimples.getText().compareTo("Pesquise por Natureza") == 0
                    || txtFieldConsultaSimples.getText().compareTo("Pesquise por Programa") == 0
                    || txtFieldConsultaSimples.getText().compareTo("Pesquise...") == 0) {
                            //txtFieldConsultaSimples.requestFocus();
                //txtFieldConsultaSimples.setForeground(Color.red);
            } else {
                consulta = txtFieldConsultaSimples.getText();
            }
        } else {
                    //txtFieldConsultaSimples.setForeground(Color.red);
            //JOptionPane.showMessageDialog(null, "O campo de busca está vazio!", "Aviso!", JOptionPane.WARNING_MESSAGE);
        }

        txtFieldConsultaSimples.setForeground(Color.gray);

        if (!jRButtonNatureza.isSelected() && !jRButtonPrograma.isSelected()) {
            JOptionPane.showMessageDialog(null, "Você precisa especificar se é Natureza ou Programa que deseja procurar!", "Aviso!", JOptionPane.WARNING_MESSAGE);
        } else {

                    // caso dê tudo certo (campo não vazio e radio button selecionado
            // ele entrará aqui...
            // aqui será feito a tabela
            ArrayList<Model.buscaNormal> resultado = null;
            buscaNormal = new buscaNormalNatureza(con);
            if (jRButtonNatureza.isSelected()) {
                resultado = buscaNormal.getBuscaNormalNatureza(consulta, jComboBoxMunicipio.getSelectedItem().toString());
            } else {
                resultado = buscaNormal.getBuscaNormalPrograma(consulta, jComboBoxMunicipio.getSelectedItem().toString());
            }

            if (resultado == null) {
                JOptionPane.showMessageDialog(null, "Nenhum resultado foi encontrado!", "Aviso!", JOptionPane.WARNING_MESSAGE);

            } else {
                // trata a tabela
                model = new DefaultTableModel();
                model.addColumn("Código");
                model.addColumn("Descrição");
                model.addColumn("Gasto");

                tblConsultaSimples.setModel(model);
                tblConsultaSimples.setEnabled(true);

                Integer i = 0;
                while (i < resultado.size()) {
                    Model.buscaNormal aux = new Model.buscaNormal();
                    aux = resultado.get(i);
                    model.addRow(new Object[]{aux.getNaturezaCodigo(), aux.getNaturezaDescricao(), "R$ "+aux.getGasto()});
                    i++;
                }

                CardLayout c3 = (CardLayout) (pnlCardLayout.getLayout());
                c3.show(pnlCardLayout, "pnlResultadoConsultaSimples");
                setTitle("Resultado Consulta Simples");
            }
        }


    }//GEN-LAST:event_btPesquisarCSimplesActionPerformed

    private void btPesquisarCAvancadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCAvancadaActionPerformed
        if (jComboBoxMunicipio2.getSelectedItem().toString().isEmpty() || txtFieldNatureza1.getText().isEmpty()
                || (!txtFieldDataInicial.getText().isEmpty() && Integer.parseInt(txtFieldDataInicial.getText()) < 2000)
                || (!txtFieldDataFinal.getText().isEmpty() && (Integer.parseInt(txtFieldDataFinal.getText()) > 2015
                || Integer.parseInt(txtFieldDataFinal.getText()) < Integer.parseInt(txtFieldDataInicial.getText())))) {
            if (jComboBoxMunicipio2.getSelectedItem().toString().isEmpty()) {
                lblMunicipio.setForeground(Color.red);
                jComboBoxMunicipio2.setForeground(Color.red);
                lblItensObrigatorios.setVisible(true);
            } else {
                lblMunicipio.setForeground(lblNatureza2.getForeground());
                jComboBoxMunicipio2.setForeground(txtFieldNatureza2.getForeground());
            }

            if (txtFieldNatureza1.getText().isEmpty()) {
                lblNatureza1.setForeground(Color.red);
                txtFieldNatureza1.setCaretColor(Color.red);
                txtFieldNatureza1.setForeground(Color.red);
                lblItensObrigatorios.setVisible(true);
            } else {
                lblNatureza1.setForeground(lblNatureza2.getForeground());
                txtFieldNatureza1.setCaretColor(txtFieldNatureza2.getCaretColor());
                txtFieldNatureza1.setForeground(txtFieldNatureza2.getForeground());
            }

            if (!txtFieldDataInicial.getText().isEmpty() && Integer.parseInt(txtFieldDataInicial.getText()) < 2000) {
                lblDataInicial.setForeground(Color.red);
                txtFieldDataInicial.setCaretColor(Color.red);
                txtFieldDataInicial.setForeground(Color.red);
                lblAnoInvalido.setVisible(true);
            } else {
                lblDataInicial.setForeground(lblNatureza2.getForeground());
                txtFieldDataInicial.setCaretColor(txtFieldNatureza2.getCaretColor());
                txtFieldDataInicial.setForeground(txtFieldNatureza2.getForeground());
            }

            if (!txtFieldDataFinal.getText().isEmpty() && (Integer.parseInt(txtFieldDataFinal.getText()) > 2015
                    || Integer.parseInt(txtFieldDataFinal.getText()) < Integer.parseInt(txtFieldDataInicial.getText()))) {
                lblDataFinal.setForeground(Color.red);
                txtFieldDataFinal.setCaretColor(Color.red);
                txtFieldDataFinal.setForeground(Color.red);
                lblAnoInvalido.setVisible(true);
            } else {
                lblDataFinal.setForeground(lblNatureza2.getForeground());
                txtFieldDataFinal.setCaretColor(txtFieldNatureza2.getCaretColor());
                txtFieldDataFinal.setForeground(txtFieldNatureza2.getForeground());
            }

        } else {
            lblMunicipio.setForeground(lblNatureza2.getForeground());
            jComboBoxMunicipio2.setForeground(txtFieldNatureza2.getForeground());
            lblNatureza1.setForeground(lblNatureza2.getForeground());
            txtFieldNatureza1.setCaretColor(txtFieldNatureza2.getCaretColor());
            txtFieldNatureza1.setForeground(txtFieldNatureza2.getForeground());
            lblItensObrigatorios.setVisible(false);
            lblAnoInvalido.setVisible(false);
            lblDataInicial.setForeground(lblNatureza2.getForeground());
            txtFieldDataInicial.setCaretColor(txtFieldNatureza2.getCaretColor());
            txtFieldDataInicial.setForeground(txtFieldNatureza2.getForeground());
            lblDataFinal.setForeground(lblNatureza2.getForeground());
            txtFieldDataFinal.setCaretColor(txtFieldNatureza2.getCaretColor());
            txtFieldDataFinal.setForeground(txtFieldNatureza2.getForeground());

            //começa daqui o banco de dados
            ArrayList<buscaAvancada> resultado = null;
            buscaAvancada = new buscaAvancadaRes(con);

            Integer dataInicial;
            Integer dataFinal;
            Integer valorInicial;
            Integer valorFinal;

            if (txtFieldDataInicial.getText().isEmpty()) {
                dataInicial = null;
            } else {
                dataInicial = Integer.parseInt(txtFieldDataInicial.getText());
            }

            if (txtFieldDataFinal.getText().isEmpty()) {
                dataFinal = null;
            } else {
                dataFinal = Integer.parseInt(txtFieldDataFinal.getText());
            }

            if (txtFieldValorInicial.getText().isEmpty()) {
                valorInicial = null;
            } else {
                valorInicial = Integer.parseInt(txtFieldValorInicial.getText());
            }

            if (txtFieldValorFinal.getText().isEmpty()) {
                valorFinal = null;
            } else {
                valorFinal = Integer.parseInt(txtFieldValorFinal.getText());
            }

	    resultado = buscaAvancada.getBuscaAvancada(txtFieldNatureza1.getText(), txtFieldNatureza2.getText(), "Campinas", dataInicial, dataFinal, valorInicial, valorFinal);

            if (resultado == null) {
                JOptionPane.showMessageDialog(null, "Nenhum resultado foi encontrado!", "Aviso!", JOptionPane.WARNING_MESSAGE);

            } else {
                // trata a tabela
                model = new DefaultTableModel();
                model.addColumn("Município");
                model.addColumn("Descrição");
                model.addColumn("Gasto");

                tblConsultaAvancada.setModel(model);
                tblConsultaAvancada.setEnabled(true);

                Integer i = 0;
                while (i < resultado.size()) {
                    buscaAvancada aux = new Model.buscaAvancada();
                    aux = resultado.get(i);
                    model.addRow(new Object[]{aux.getDescricaoInternaMunicipio(), aux.getDescricaoNatureza(), "R$ "+aux.getGasto()});
                    i++;
                }

                CardLayout c3 = (CardLayout) (pnlCardLayout.getLayout());
                c3.show(pnlCardLayout, "pnlResultadoConsultaAvancada");
                setTitle("Resultado Consulta Avançada");
            }
        }
    }//GEN-LAST:event_btPesquisarCAvancadaActionPerformed

    private void txtFieldValorFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldValorFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldValorFinalActionPerformed

    private void txtFieldNatureza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNatureza2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNatureza2ActionPerformed

    private void btHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoActionPerformed

        btHistorico.setBackground(new java.awt.Color(0, 0, 51));
        btConsultaAvancada.setBackground(new java.awt.Color(0, 102, 153));
        btConsultaSimples.setBackground(new java.awt.Color(0, 102, 153));

        ArrayList<Model.historico> resultado = null;
        historico = new consultaHistorico(con);

        resultado = historico.getHistorico();

        if (resultado == null) {
            JOptionPane.showMessageDialog(null, "Não há histórico!", "Aviso!", JOptionPane.WARNING_MESSAGE);

        } else {
            // trata a tabela
            model = new DefaultTableModel();
            model.addColumn("Tipo de Consulta");
            model.addColumn("Consulta Realizada");
            model.addColumn("Data"); //tratar depois
            model.addColumn("Horário"); //tratar depois

            tblConsultaHistorico.setModel(model);
            tblConsultaHistorico.setEnabled(true);

            Integer i = 0;
            while (i < resultado.size()) {
                Model.historico aux = new Model.historico();
                aux = resultado.get(i);
                model.addRow(new Object[]{aux.getTipo_consulta(), aux.getTexto_consulta(), aux.getData(), aux.getHora()});
                i++;
            }

            CardLayout c2 = (CardLayout) (pnlCardLayout.getLayout());
            c2.show(pnlCardLayout, "pnlHistorico");
            setTitle("Histórico");
        }

    }//GEN-LAST:event_btHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public class RoundedPanel extends JPanel {

        private static final long serialVersionUID = 1L;
        /**
         * Stroke size. it is recommended to set it to 1 for better view
         */
        protected int strokeSize = 1;
        /**
         * Color of shadow
         */
        protected Color shadowColor = Color.black;
        /**
         * Sets if it drops shadow
         */
        protected boolean shady = true;
        /**
         * Sets if it has an High Quality view
         */
        protected boolean highQuality = true;
        /**
         * Double values for Horizontal and Vertical radius of corner arcs
         */
        protected Dimension arcs = new Dimension(10, 10);
        /**
         * Distance between shadow border and opaque panel border
         */
        protected int shadowGap = 4;
        /**
         * The offset of shadow.
         */
        protected int shadowOffset = 4;
        /**
         * The transparency value of shadow. ( 0 - 255)
         */
        protected int shadowAlpha = 100;

        protected int idCounter = 0;

        // FOLLOWING CODES GOES HERE
        public RoundedPanel() {
            super();
            setOpaque(false);
        }

        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            int width = getWidth();
            int height = getHeight();
            int shadowGap = this.shadowGap;
            Color shadowColorA = new Color(shadowColor.getRed(),
                    shadowColor.getGreen(), shadowColor.getBlue(), shadowAlpha);
            Graphics2D graphics = (Graphics2D) g;

            // Sets antialiasing if HQ.
            if (highQuality) {
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON);
            }

            // Draws shadow borders if any.
            if (shady) {
                graphics.setColor(shadowColorA);
                graphics.fillRoundRect(shadowOffset,// X position
                        shadowOffset,// Y position
                        width - strokeSize - shadowOffset, // width
                        height - strokeSize - shadowOffset, // height
                        arcs.width, arcs.height);// arc Dimension
            } else {
                shadowGap = 1;
            }

            // Draws the rounded opaque panel with borders.
            graphics.setColor(getBackground());
            graphics.fillRoundRect(0, 0, width - shadowGap, height - shadowGap,
                    arcs.width, arcs.height);
            graphics.setColor(getForeground());
            graphics.setStroke(new BasicStroke(strokeSize));
            graphics.drawRoundRect(0, 0, width - shadowGap, height - shadowGap,
                    arcs.width, arcs.height);

            // Sets strokes to default, is better.
            graphics.setStroke(new BasicStroke());
        }
    }

    public class RoundJTextField extends JTextField {

        private Shape shape;

        public RoundJTextField(int size) {
            super(size);
            setOpaque(false); // As suggested by @AVD in comment.
        }

        protected void paintComponent(Graphics g) {
            g.setColor(getBackground());
            g.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
            super.paintComponent(g);
        }

        protected void paintBorder(Graphics g) {
            g.setColor(getForeground());
            g.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
        }

        public boolean contains(int x, int y) {
            if (shape == null || !shape.getBounds().equals(getBounds())) {
                shape = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, 15, 15);
            }
            return shape.contains(x, y);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultaAvancada;
    private javax.swing.JButton btConsultaSimples;
    private javax.swing.ButtonGroup btGroup;
    private javax.swing.JButton btHistorico;
    private javax.swing.JButton btPesquisarCAvancada;
    private javax.swing.JButton btPesquisarCSimples;
    private javax.swing.JComboBox jComboBoxMunicipio;
    private javax.swing.JComboBox jComboBoxMunicipio2;
    private javax.swing.JRadioButton jRButtonNatureza;
    private javax.swing.JRadioButton jRButtonPrograma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnoInvalido;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblItensObrigatorios;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblMunicipioSimples;
    private javax.swing.JLabel lblNatureza1;
    private javax.swing.JLabel lblNatureza2;
    private javax.swing.JLabel lblRodape;
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JLabel lblValorInicial;
    private javax.swing.JPanel pnlBordaBotoes;
    private javax.swing.JPanel pnlCardLayout;
    private javax.swing.JPanel pnlConsultaAvancada;
    private javax.swing.JPanel pnlConsultaSimples;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHistorico;
    private javax.swing.JPanel pnlLabelMenuConsultas;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlResultadoConsultaAvancada;
    private javax.swing.JPanel pnlResultadoConsultaSimples;
    private javax.swing.JTable tblConsultaAvancada;
    private javax.swing.JTable tblConsultaHistorico;
    private javax.swing.JTable tblConsultaSimples;
    private javax.swing.JTextField txtFieldConsultaSimples;
    private javax.swing.JTextField txtFieldDataFinal;
    private javax.swing.JTextField txtFieldDataInicial;
    private javax.swing.JTextField txtFieldNatureza1;
    private javax.swing.JTextField txtFieldNatureza2;
    private javax.swing.JTextField txtFieldValorFinal;
    private javax.swing.JTextField txtFieldValorInicial;
    // End of variables declaration//GEN-END:variables
}
